main/main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from music.models import Music


class CustomUser(AbstractUser):
    username = models.CharField(max_length=40, unique=True)
    phone_number=models.CharField(max_length=11,null=True,unique=True)
    email=models.EmailField(null=True,unique=True)
    favorites = models.ManyToManyField(Music, blank=True)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

@receiver(pre_delete, sender=CustomUser)
def remove_favorites_on_customer_delete(sender, instance, **kwargs):
    instance = CustomUser.objects.get(id=instance.id)
    for music in instance.favorites.all():
        music.decrement_favorite_count()

main/templates/deneme.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Musicfy</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/spotify.css'%}">
    <style>
        .logo a {
            display: inline-block;
            margin-right: 10px;
            margin-left:0px;
            color: white;
            font-size: 24px;
        }
        .logo a i {
            font-size: 42px;
            vertical-align: middle;
        }
    </style>
  </head>
  <body>

    <aside class="sidenav">
        <div class="logo">
            <a href="{% url "home_page" %}" style="color: white; font-size: 24px;">
              <i class="fas fa-music"></i> Musicfy
            </a>
        </div>
        <div style="display: flex; align-items: center;">
            <a href="#" style="margin-right: 10px;"><i class="fas fa-search"></i></a>
            <input style="width:200px;" type="text" id="music-search" class="form-control" placeholder="Şarkı Ara">
        </div>
    
        <br>
      <div class="menulink">
        {% if user.is_authenticated %}
        <a href="{% url 'profile_page' %}"><i class="fas fa-user" style="color: white;"></i> <span>Profil</span> </a>
        <a href="{% url "favorite_page" %}"><i class="fas fa-heart " style="color: white;"></i> <span>Favoriler</span></a>
        <a href="{% url 'logout_page' %}"><i class="fas fa-sign-out-alt " style="color: white;"></i> <span>Çıkış Yap</span></a>
        {% endif %} 
       

      </div>
      <div class="buttons">
        {% if not user.is_authenticated %}
            <a href="{% url "signup_page" %}"><button type="button" class="btn btn-light">Üye Ol</button></a>
            <a href="{% url "login_page" %}"><button type="button" class="btn btn-dark">Giriş Yap</button></a>
        {% endif %}
    </div>
    </aside>

    <main>
      <div class="container-flex ptb-30 plb-20">
        <div class=" toplist">
          <ul class="list-inline">
            <li><a href="{% url "home_page" %}">Ana Sayfa</a></li>          
            <li>
                <div style="display: flex; align-items: center;">
                  <a href="#"><i class="fas fa-search"></i></a>
                  <input type="text" placeholder="Arama Yap">
                </div>
            </li>
          </ul>
        </div>
      </div>
        <div class="title plb-20">
          <h1><strong>Şarkı</strong></h1>
        </div>
        <div class=" container-flex text-center">
                <div class="music-card">
                <a href="#"><img src="{% static 'img/motivation.png' %}" alt=""></a>
                <h6>{{only_music.title}}</h6>
                <p>{{only_music.release}}</p>
                <button class="playPauseButton" data-music-id="{{ only_music.id }}" data-param={{ only_music.youtube_id }}>▶️</button>
                <button class="btn btn-outline-danger favorite-btn" data-music-id="{{ only_music.id }}"
                {% if not request.user.is_authenticated %}
                    onclick="location.href='{% url 'login_page' %}'"
                {% else %}
                    onclick="toggleFavorite(this)"
                    {% if only_music.id in favorite_musics %}
                        data-favorited="true"
                    {% else %}
                        data-favorited="false"
                    {% endif %}
                {% endif %}>
              </div>
              
        </div> 
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    </main>


    
    <footer id="mainFooter">
      <div class="container">
          <div class="row align-items-center">
              <div class="col-md-3">
                  <div id="selectedSongName">
                      <p>SELAM<p>
                  </div>
                  <div id="selectedSongRelease">
                      <p>SELAM<p>
                  </div>

              </div>
              <div class="col-md-6">
                  <div class="playmusic text-center">
                      <ul class="list-inline">
                          <li><button id="beforeButton" class="button-style"><i class="fas fa-step-backward"></i></button></li>
                          <li><button id="playPauseButton"><span id="playPauseIcon">▶️</span></button></li>
                          <li><button id="nextButton" class="button-style"><i class="fas fa-step-forward"></i></button></li>                
                      </ul>
                      <div style="width:250px; margin: 0 auto;">
                          <div id="progress-container">
                              <span id="current-time">0:00</span>
                              <div><input type="range" value="0" min="0" max="60"></div>
                              <span id="duration">0:00</span>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-3">
                  <div id="songName"></div>
              </div>
              
          </div>
      </div>
    </footer>
  
 
    <script async src="https://www.youtube.com/iframe_api"></script>
    <script>
        let player;
        let isPlaying = false;
        let general_play=false;
        var currentVideoId;
        var currentSongIndex = 0;
        var footer = document.getElementById("mainFooter");
        var pause_button = document.getElementById("playPauseButton");
        main_button=document.getElementById("playPauseIcon") 
        var last_button;
        const rangeInput = document.querySelector('#progress-container input[type="range"]');


        var playlist_id = JSON.parse('{{ playlist_id|escapejs }}');
        var playlist_title= JSON.parse('{{ playlist_title|escapejs }}');
        var playlist_release=JSON.parse('{{ playlist_release|escapejs }}');
        
        var video_id="{{ only_music.youtube_id }}"
        console.log("video id şu",video_id)
        footer.style.display = "block";
        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                height: '0',
                width: '0',
                videoId: '', // YouTube video ID
                events: {
                    'onReady': onPlayerReady
                }
            });
        }
        function onPlayerReady(event) {
            setInterval(updateTimeDisplay, 1000);
        };
        rangeInput.addEventListener('input', function() {
            const newValue = this.value;
            // Şarkının o saniyeye gitmesi için player'ın oynatma pozisyonunu ayarlayın
            player.seekTo(newValue, true);
        });

        // Her bir buton için olay dinleyicisi ekle
        main_button.addEventListener("click", function() {
            if (isPlaying) {
                player.pauseVideo();
                last_button.innerText = '▶️';
                main_button.innerText = '▶️';
                isPlaying=false
            } else {
                player.playVideo();
                last_button.innerText = '⏸️';
                main_button.innerText = '⏸️';
                isPlaying = true;
            }
        });
       
        
  
        pause_button.addEventListener("click", function() {
                console.log("pause butonu clickledin")
                if (!general_play) {
                    footer.style.display = "block";
                    general_play = true;
                }
                else{
                    if (last_button!=button){
                        isPlaying=false
                        last_button.innerText = '▶️';
                    }
                }    
                var songName = this.parentElement.querySelector('h6').textContent;
                var songRelease = this.parentElement.querySelector('p').textContent;
                document.getElementById('selectedSongName').innerHTML = '<h6>' + songName + '</h6>';
                document.getElementById('selectedSongRelease').innerHTML = '<p>' + songRelease + '</p>';
                last_button=button
                var videoId = this.getAttribute("data-param");
                togglePlayPause(this, videoId);
  
        });
        
        document.getElementById('nextButton').addEventListener('click', function() {  
            currentSongIndex++;
            if (currentSongIndex >= playlist_id.length) {
                currentSongIndex = 0;
            }
            var nextSongId = playlist_id[currentSongIndex]
            var nextSongTitle=playlist_title[currentSongIndex]
            var nextSongRelease=playlist_release[currentSongIndex]
            document.getElementById('selectedSongName').innerHTML = '<h6>' + nextSongTitle + '</h6>';
            document.getElementById('selectedSongRelease').innerHTML = '<p>' + nextSongRelease + '</p>';
            if (nextSongId !== null) { 
                if (currentVideoId !== nextSongId ) {
                    player.loadVideoById(nextSongId);
                    currentVideoId = nextSongId;
                    isPlaying=false
                }
            }
            if (isPlaying) {
                player.pauseVideo();
                isPlaying = false;
                main_button.innerText = '▶️';
            } else {
                player.playVideo();
                isPlaying = true;
                main_button.innerText = '⏸️';
            }
        });
        document.getElementById('beforeButton').addEventListener('click', function() {
       
           
            currentSongIndex--;
            if (currentSongIndex <= 0) {
                currentSongIndex = playlist_id.length;
            }
            var nextSongId = playlist_id[currentSongIndex]
            var nextSongTitle=playlist_title[currentSongIndex]
            var nextSongRelease=playlist_release[currentSongIndex]
            document.getElementById('selectedSongName').innerHTML = '<h6>' + nextSongTitle + '</h6>';
            document.getElementById('selectedSongRelease').innerHTML = '<p>' + nextSongRelease + '</p>';

            if (currentVideoId !== nextSongId) {
                player.loadVideoById(nextSongId);
                currentVideoId = nextSongId;
                isPlaying=false
            }
            if (isPlaying) {
                player.pauseVideo();
                isPlaying = false;
                main_button.innerText = '▶️';
            } else {
              
                player.playVideo();
                isPlaying = true;
                main_button.innerText = '⏸️';
            }
        });
        function togglePlayPause(button, videoId) {
            if (currentVideoId !== videoId) {
                player.loadVideoById(videoId);
                currentVideoId = videoId;
            }
            if (isPlaying) {
                player.pauseVideo();
                isPlaying = false;
                main_button.innerText = '▶️';
                button.innerText = '▶️';
            } else {
                player.playVideo();
                isPlaying = true;
                main_button.innerText = '⏸️';
                button.innerText = '⏸️';
            }
        }

        function updateTimeDisplay() {
            const currentTime = player.getCurrentTime();
            const duration = player.getDuration();
            const currentTimeFormatted = formatTime(currentTime);
            const durationFormatted = formatTime(duration);
            rangeInput.setAttribute('value', Math.floor(currentTime));
            rangeInput.setAttribute('max', Math.floor(duration));
            document.getElementById('duration').textContent = durationFormatted;
            document.getElementById('current-time').textContent = currentTimeFormatted;
        }
        function formatTime(time) {
            const minutes = Math.floor(time / 60);
            const seconds = Math.floor(time % 60);
            return `${minutes < 10 ? '0' : ''}${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;
        }
    </script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          document.querySelectorAll('.favorite-btn').forEach(button => {
             
              if (button.dataset.favorited === 'true') {
                  button.style.backgroundColor = 'red';
              }
              else{
                  button.style.backgroundColor = 'white';
              }
          });
      });

      function toggleFavorite(button) {
          const musicSlug = button.getAttribute('data-music-id');
          console.log(musicSlug)
          fetch('/add_or_remove_favorite/', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
                  'X-CSRFToken': '{{ csrf_token }}'
              },
              body: JSON.stringify({ music_slug: musicSlug })
          })
          .then(response => response.json())
          .then(data => {
              if (data.status === 'added') {
                  button.style.backgroundColor = 'red'; 
                  button.classList.add('favorited');
              } else if (data.status === 'removed') {
                  button.style.backgroundColor = 'white'; 
                  button.classList.remove('favorited');
              }
          })
          .catch(error => console.error('Hata:', error));
      }
     
      
  </script>
</body>
</html>

main/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Musicfy - Giriş Yap</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <style>
        .musics-icon {
            position: absolute;
            top: 50px;
            left: 50px;
            font-size: 44px;
            color: #1db954;
        }
    </style>
</head>
<body>
    <a href="{% url 'home_page' %}">
        <i class="fas fa-music musics-icon"></i>
    </a>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2 class="text-center">Musicfy - Sign In</h2>
                <div class="center card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Sign In</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

main/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profil</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <style>
        .logo a {
            display: inline-block;
            margin-right: 10px;
            margin-left:0px;
            color: white;
            font-size: 24px;
        }
        .logo a i {
            font-size: 42px;
            vertical-align: middle;
        }
    </style>
</head>
<body>
    <aside class="sidenav">
        <div class="logo">
            <a href="{% url 'home_page' %}" style="color: white; font-size: 24px;">
                <i class="fas fa-music"></i> Musicfy
            </a>
        </div>
        <br>
        <div class="buttons">
            {% if user.is_authenticated %}
                <button onclick="window.location.href='{% url 'profile_page' %}'" type="button" class="btn btn-light"><i class="fas fa-user"></i> <span>Profile</span></button>
                <button onclick="window.location.href='{% url 'favorite_page' %}'" type="button" class="btn btn-light"><i class="fas fa-heart"></i> <span>Favorites</span></button>
                <button onclick="window.location.href='{% url 'logout_page' %}'" type="button" class="btn btn-dark"><i class="fas fa-sign-out-alt"></i> <span>Sign Out</span></button>
            {% endif %}
        </div> 
        <div class="buttons">
            {% if not user.is_authenticated %}
                <a href="{% url "signup_page" %}"><button type="button" class="btn btn-light">Sign Up</button></a>
                <a href="{% url "login_page" %}"><button type="button" class="btn btn-dark">Sign In</button></a>
            {% endif %}
        </div>
        <div class="buttons">
            <!-- Profile sayfasında aynı kullanıcıyı tekrar oluşturmamak için butonları kaldırın -->
        </div>
    </aside>

    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <h2 class="text-center">Profile</h2>
                    <div class="center">
                        <div>
                            <div>
                                <label>Username: {{ user.username }}</label>
                            </div>
                            <div>
                                <label>Name: {{ user.first_name }}</label>
                            </div>
                            <div>
                                <label>Surname: {{ user.last_name }}</label>
                            </div>
                            <div>
                                <label>Email: {{ user.email }}</label>
                            </div>
                            <div>
                                <label>Phone Number: {{ user.phone_number }}</label>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
    </main>

</body>
</html>

main/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Musicfy - Sign Up</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <style>
        .music-icon {
            position: absolute;
            top: 50px;
            left: 50px;
            font-size: 44px;
            color: #1db954;
        }
    </style>
</head>
<body>
    <a href="{% url 'home_page' %}">
        <i class="fas fa-music music-icon"></i>
    </a>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2 class="text-center">Musicfy - Sign Up</h2>
                <div class="center">
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <label for="id_user_name">Username:</label>
                            {{ form.username }}
                            {% if form.username.errors %}
                                <ul class="errors">
                                    {% for error in form.username.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_first_name">First Name:</label>
                            {{ form.first_name }}
                            {% if form.first_name.errors %}
                                <ul class="errors">
                                    {% for error in form.first_name.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_last_name">Last Name:</label>
                            {{ form.last_name }}
                            {% if form.last_name.errors %}
                                <ul class="errors">
                                    {% for error in form.last_name.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <ul class="errors">
                                    {% for error in form.email.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_phone_number">Phone Number:</label>
                            {{ form.phone_number }}
                            {% if form.phone_number.errors %}
                                <ul class="errors">
                                    {% for error in form.phone_number.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_password1">Password:</label>
                            {{ form.password1 }}
                            {% if form.password1.errors %}
                                <ul class="errors">
                                    {% for error in form.password1.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div>
                            <label for="id_password2">Password Confirmation:</label>
                            {{ form.password2 }}
                            {% if form.password2.errors %}
                                <ul class="errors">
                                    {% for error in form.password2.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <button type="submit">Sign Up</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</body>
</html>